In [34]:
import numpy as np


In [35]:
A = np.matrix([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
type(A)

print("Matrix")
print(A)
print("Acess")
print(A[0,1])
print(A[1])
print(A[1,:])
print(A[1,:])
print(A[:,0])








Matrix
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Acess
2
[[5 6 7 8]]
[[5 6 7 8]]
[[5 6 7 8]]
[[1]
 [5]
 [9]]


In [36]:
print("Matrix")
print(A)
print("Acesso [0:2,1]")
print(A[0:2,1])
print("Acesso [0:2,1:4:2]")
print(A[0:2,1:4:2])
print("Mostrando a matriz com as linhas reversas")
print(A[::-1,:]) 


Matrix
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Acesso [0:2,1]
[[2]
 [6]]
Acesso [0:2,1:4:2]
[[2 4]
 [6 8]]
Mostrando a matriz com as linhas reversas
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [37]:
Z = np.zeros((4,5))
Z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
import numpy.random as npr

N =np.matrix ( npr.randint(-10,10,(3,2)))
N

matrix([[ 1,  9],
        [ 3,  2],
        [ 2, -8]])

In [39]:
N =np.matrix ( npr.randint(-10,10,(3,2)))
N

matrix([[ 6,  6],
        [-5,  3],
        [-1,  8]])

In [40]:
# Lembre que python é orientado a objetos. Assim uma simples atribuições entre duas matrizes faz com que abas apontem para o mesmo objeto
B=A
print(A)
print(B)

print("Mudando o valor de A - veja que B foi modificado também")
A[0,0] = -100
print(A)
print(B)

print("Mudando o valor de B - veja que A foi modificado também")
B[0,0] = 30
print(A)
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mudando o valor de A - veja que B foi modificado também
[[-100    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
[[-100    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]
Mudando o valor de B - veja que A foi modificado também
[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
C = np.matrix(A)
print(A)
print(C)
print("Mudando o valor de A - veja que C não será afetada")
A[0,0] = 50;
print(A)
print(C)


print("Mudando o valor de C - veja que A não será afetada")
C[0,0] = 100;
print(A)
print(C)

[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mudando o valor de A - veja que C não será afetada
[[50  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[30  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mudando o valor de C - veja que A não será afetada
[[50  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [42]:
M = np.matrix(Z)
print("Matriz M:")
print(M)
print("Matriz N: ")
print(N)
M[0:3, 0:3:2] = N
print("Matrix M após a atribuição em bloco: da linha zero até a linha 3, da coluna 2 até a 4")
print(M)

Matriz M:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriz N: 
[[ 6  6]
 [-5  3]
 [-1  8]]
Matrix M após a atribuição em bloco: da linha zero até a linha 3, da coluna 2 até a 4
[[ 6.  0.  6.  0.  0.]
 [-5.  0.  3.  0.  0.]
 [-1.  0.  8.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [43]:
B = np.matrix(np.eye(2,2))
print(B)
print(np.matrix( np.eye(10,10)))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [44]:
A = np.matrix([[1,1],[2,3]])
print(A)
print(B)
B= 4*B
B

[[1 1]
 [2 3]]
[[1. 0.]
 [0. 1.]]


matrix([[4., 0.],
        [0., 4.]])

In [45]:
print(A)
print(B)

C =  A + B
C

[[1 1]
 [2 3]]
[[4. 0.]
 [0. 4.]]


matrix([[5., 1.],
        [2., 7.]])

In [46]:
print(A)
print(B)

D = A * B
D

[[1 1]
 [2 3]]
[[4. 0.]
 [0. 4.]]


matrix([[ 4.,  4.],
        [ 8., 12.]])

In [47]:
print(A)
print(B)

E = A**2 
E

[[1 1]
 [2 3]]
[[4. 0.]
 [0. 4.]]


matrix([[ 3,  4],
        [ 8, 11]])

In [48]:
print(A)
Ainversa = A**-1
print(Ainversa)
print(A * Ainversa)

[[1 1]
 [2 3]]
[[ 3. -1.]
 [-2.  1.]]
[[1. 0.]
 [0. 1.]]


In [49]:
A
print(A)
print(np.transpose(A))

[[1 1]
 [2 3]]
[[1 2]
 [1 3]]


In [50]:
print(A)
np.trace(A)

[[1 1]
 [2 3]]


np.int64(4)

In [ ]:
print(A)
print(B)
np.hstack( (A, B) )

In [ ]:
print(A)
print(B)
np.vstack(  (A,B)   )

In [ ]:
print(A)

np.sqrt(A)